### PR TITLE
Added Feature host tab

### PR DESCRIPTION
**Pull request by OsOmE1**

### CODE REVIEW

**Comment by v0idp** [comment]
can you post a screenshot of the tab how it looks ingame ?

**Comment by OsOmE1** [comment]
Feature nr 1. You can change the map while in the lobby.
image
image

Feature nr 2. You can select who are going to be the impostors.
image
image

**Comment by std-nullptr** [comment]
Can you change `State.impostors` so that it isn't a `std::vector<PlayerControl*>`. State should not contain pointers to in-game objects as there is no guarantee they will persist properly. What if you selected a player and they left the lobby before you started? I would recommend doing a `std::vector<uint8_t>` and storing them by Player Id then using `GetPlayerDataById` to get the `GameData_PlayerInfo*`.

**Comment by v0idp** [comment]
could we also make the tab available while being in Lobby ? @std-nullptr

**Comment by OsOmE1** [comment]
> could we also make the tab available while being in Lobby only ? @std-nullptr

it is only available in the lobby the IsHost() function returns true only if you are in a lobby

**Comment by v0idp** [comment]
> > could we also make the tab available while being in Lobby only ? @std-nullptr
> 
> it is only available in the lobby the IsHost() function returns true only if you are in a lobby

You probably want to seperate isHost and isInLobby

**Pull request closed without merging**
